### ISSUE TITLE
[react-native] TypeError: IMaskMixin__default['default'] is not a function

### ISSUE THREAD

**Issue by maximzhemerenko** [uNmAnNeR/imaskjs#462]
Got this error after upgrade from 'react-native-imask' 6.0.5 to 6.0.6: `TypeError: IMaskMixin__default['default'] is not a function. (In 'IMaskMixin__default['default'](MaskedComponent)', 'IMaskMixin__default['default']' is an instance of Object)`.

This issue also exists in version 6.0.7. Tested on fresh installation of react-native 0.63.4
<img width="413" alt="image" src="https://user-images.githubusercontent.com/7162289/111079198-9ff49580-8501-11eb-9e5c-8ed8ea5c2f13.png">
<img width="543" alt="image" src="https://user-images.githubusercontent.com/7162289/111079216-aedb4800-8501-11eb-96dd-585b843c61cc.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/7162289/111079230-bd296400-8501-11eb-8497-1dfe7b1c251a.png">

**Comment by aplinxy9plin** [comment]
+1

**Comment by sebak94** [comment]
Same

**Comment by maximzhemerenko** [comment]
@uNmAnNeR thank you!

**Comment by diejsel** [comment]
![image](https://user-images.githubusercontent.com/8231501/129612508-bf66687a-556d-4a1b-9d95-3b5b400ff1a5.png)
![image](https://user-images.githubusercontent.com/8231501/129612576-40f8c280-2c72-4428-8412-01019a8a77eb.png)

Similar bug in version 6.1.0 in android emulator. Works well on the web.

**Comment by diejsel** [comment]
![image](https://user-images.githubusercontent.com/8231501/129620231-95624639-80e9-4d8d-8fe2-48124182a789.png)
![image](https://user-images.githubusercontent.com/8231501/129620319-47207f10-858e-40bc-ad94-31ed0367eb75.png)

Everything works as it should, only an error occurs: native-mask-element-c27b64cf.js:139 Uncaught TypeError: this.input.setNativeProps is not a function

**Comment by uNmAnNeR** [comment]
@diejsel hey! if you have time please check if issues from that comment was solved or not https://github.com/uNmAnNeR/imaskjs/issues/12#issuecomment-393791838
if they are solved then i will try to get it working again. There should be a lot of updates in react native since i have not been checking it for the last 2 years.

**Comment by diejsel** [comment]
check, all issues as resolved
